version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: customer_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: customer_crud_app
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - customer_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: customer_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - database
    networks:
      - customer_network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=customer_crud_app
      - DB_USERNAME=laravel
      - DB_PASSWORD=password

  controller:
    image: nginx:alpine
    container_name: customer_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - customer_network

  searcher:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: customer_elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - customer_network

volumes:
  mysql_data:
    driver: local
  es_data:
    driver: local

networks:
  customer_network:
    driver: bridge